### ISSUE TITLE
I want to have such bar for working hours. How to get this? 

### ISSUE THREAD

**Issue by Rsl717** [Vinctor/VCharts#1]
I have the same issue. I want to have such bar for working hours. How to get this? And whether it is possible to put a filter there ? for filtering out monthly/weekly

![](https://cloud.githubusercontent.com/assets/21261181/26141907/89d56f34-3af7-11e7-94a8-261875606e80.PNG)

**Comment by Vinctor** [comment]
this is a horizontal bar chart . you can draw it by giving data from server or other data source,.
1.compute the width of peer hour;
2.Dynamic draw the bra according the data;

or,you can description your demand,i can create it when i'm fress.
